namespace: go-k6

replicaCount: 1

image:
  repository: 16181181418/go-k6-grafana
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080

resources:
  limits:
    cpu: "0.5"
    memory: "256Mi"
  requests:
    cpu: "0.25"
    memory: "128Mi"

