services:
  server:
    container_name: go-test-server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5" # Limit the container to 50% of a single CPU
          memory: "256M" # Limit the container to 256MB of memory
    restart: always
    networks:
      - testnet

  k6:
    container_name: go-test-k6
    image: grafana/k6
    volumes:
      - ./k6:/scripts
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "1G"
    entrypoint: [ "/bin/sh", "-c", "tail -f /dev/null" ]
    networks:
      - testnet
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - testnet

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - testnet
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

networks:
  testnet:
    driver: bridge

volumes:
  grafana-data: