services:
  server:
    container_name: go-test-server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5" # Limit the container to 50% of a single CPU
          memory: "256M" # Limit the container to 256MB of memory
    restart: always
    networks:
      - testnet

  k6:
    container_name: go-test-k6
    image: grafana/k6
    volumes:
      - ./k6:/scripts
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4G"
    entrypoint: [ "/bin/sh", "-c", "tail -f /dev/null" ]
    networks:
      - testnet
    
networks:
  testnet: