# service.yml
apiVersion: v1
kind: Service
metadata:
  name: go-k6-grafana-server
  namespace: go-k6
spec:
  selector:
    app: go-k6-grafana-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
