apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grafana-server
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-grafana-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-grafana-server
    spec:
      containers:
        - name: {{ .Release.Name }}-grafana-server
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: PORT
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      restartPolicy: Always
